export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const EDIT_GENRE = 'EDIT_GENRE';
export const ADD_GENRE_SUCCESS = 'CREATE_GENRE_SUCCESS';
export const DELETE_GENRE_SUCCESS = 'DELETE_GENRE_SUCCESS';
export const CREATE_MOVIE = 'CREATE_MOVIE_SUCCESS';
export const DELETE_MOVIE = 'DELETE_MOVIE_SUCCESS';
