export const LOAD_GENRES = 'LOAD_GENRES_SUCCESS';
export const LOAD_MOVIES = 'LOAD_MOVIES_SUCCESS';
export const UPDATE_GENRE = 'UPDATE_GENRE_SUCCESS';
export const CREATE_GENRE = 'CREATE_GENRE_SUCCESS';
export const DELETE_GENRE = 'DELETE_GENRE_SUCCESS';
export const CREATE_MOVIE = 'CREATE_MOVIE_SUCCESS';
export const DELETE_MOVIE = 'DELETE_MOVIE_SUCCESS';
