export const LOAD_GENRES_SUCCESS = 'LOAD_GENRES_SUCCESS';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const UPDATE_GENRE_SUCCESS = 'UPDATE_GENRE_SUCCESS';
export const CREATE_CAT_SUCCESS = 'CREATE_GENRE_SUCCESS';
export const DELETE_CAT_SUCCESS = 'DELETE_GENRE_SUCCESS';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
